services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    restart: unless-stopped

volumes:
  qdrant-storage:
  qdrant-snapshots:
